### ISSUE TITLE
SteamVR crashes with error 119

### ISSUE THREAD

**Issue by Avenred** [DevOculus-Meta-Quest/OculusKiller#6] opened 2023-11-28 03:19 UTC
When launching quest link from the headsets side with OculusKiller installed, SteamVR will crash and fail to start, which then causes the headset to go back home and not start quest link:
![vrmonitor_1701141453_3568](https://github.com/DevOculus-Meta-Quest/OculusKiller/assets/13921970/d2f4dc4f-07bc-407b-b81c-08334fc75170)

This can sometimes be fixed by closing Steam, closing Oculus, then opening Oculus and Steam in that order, and trying again.

Headset: Quest 2
CPU: Ryzen 6 5600
GPU: Geforce RTX 4060ti
Windows 11 version 23H2

**Comment by Eliminater74** [comment] 2023-11-29 03:04
Did you check the logs, Logs: All log files are located at C:\Users\<USERNAME>\AppData\Local\OculusKiller\OculusKiller.log

can you paste your logs in here, also are you on SteamVR Beta or Normal? The OculusKiller is designed to Monitor the SteamVR Process and restart them if they crash. it will try and restart them 3 times before giving up and closing out OculusLink.
so seeing that log might give me a bit more info I hope. and did this just recently start or has it been happening.
I havent tested it for at least 2 weeks now. since I have tested it many times since my last update and no issues.
So is it possible SteamVR updated again. that I dont know. I will have to test again and see whats up.
SteamVR has been very unstable since its new 2.x UI release.. I have had it crash without even using OculusKiller.
that is the whole reason I added that Monitor watchdog to restart it upon a crash detected...... Guess I will have to add more
logging and see if we can track this down if needed........

**Comment by Avenred** [comment] 2023-11-29 16:27
Here are the logs from the session: https://pastebin.com/raw/S9dX5BG0
SteamVR has also been fairly unstable for me after the 2.0 release as well. I am running the normal branch, not the beta one too. This has been happening for about a month now, although recently it has gotten more frequent, and it seems restarting everything doesn't fix it either.

**Comment by Eliminater74** [comment] 2023-11-29 16:57
something is defiantly messed up,

your logs, 
11/28/2023 18:38:09: Successfully started process: C:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\win64\vrstartup.exe
11/28/2023 18:38:09: Started SteamVR using vrstartup.exe
11/28/2023 18:38:14: Monitoring vrserver and vrdashboard processes.
11/28/2023 20:16:06: An error occurred: Process was not started by this object, so requested information cannot be determined.
11/28/2023 20:16:06: vrserver or vrdashboard process not found. Starting...
11/28/2023 20:16:06: Successfully started process: C:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\win64\vrserver.exe
11/28/2023 20:16:06: An error occurred: Object reference not set to an instance of an object.
11/28/2023 20:16:06: Maximum retry limit reached. Terminating SteamVR and Oculus Air Link.

I see alot of  Maximum retry limit reached. Terminating SteamVR and Oculus Air Link.
and some of this, An error occurred: Cannot process request because the process (22784) has exited.
as well as this,  An error occurred: Cannot process request because the process (6492) has exited.

this is strange too, An error occurred: Access is denied

I will have to do some testing and see whats going on. Might have to add a bit more logging. and 
possible change the timing..

if its possible, can you reinstall SteamVR pretty much uninstall it and remove all data that has to do with it from your
userdata section. then reinstall SteamVR. and try again.. you might wanna clear your OculusKiller log before trying again..

in the meantime I will do some testing and see whats up. as I said I might have to change the timing and have more logging.
Let me know how the above goes if you so do try that. if you dont want to try that, Just wait for my update. 

but I truly think its on the SteamVR side. but at least I can try and find the reason and see if we can work around it..

**Comment by Avenred** [comment] 2023-11-29 22:46
Still having the same issue. This is after reinstalling SteamVR. I might try the beta version next to see if that fixes anything?
Here is the new logs (after 1 attempt at trying to start OculusKiller): https://pastebin.com/raw/VYVFKYZ5

**Comment by Eliminater74** [comment] 2023-11-30 01:20
them logs are pretty normal. I just tested my last 3 versions. and had no issues. I did manage to fix a few things and add a bit better logging. but as to your problem I just dont get it. I played like 4 games and didnt have a single issue. I will admit I am running Beta Steam and Beta SteamVR. but I really doubt thats the issue. and I havent heard from others yet.. If you have anyone you know that uses this, can you check with them and see if any problems like yours.

I updated again since the last update earlier. wanted to enhance logging again to understand whats going on. For some reason,  SteamVR is exiting on you and that makes no seance. Well try this next one and see if anything changes.. but I really think the problem is on Steam's side.. Most likely the SteamVR. Let me know on next update..

**Comment by Avenred** [comment] 2023-12-01 16:16
I updated to the beta version of SteamVR and also updated Oculus Killer to the latest version and I've since had no issues. Not sure what was changed in the last version, but it seems to be working now!

**Comment by Eliminater74** [comment] 2023-12-01 18:15
I am glad that helped you. hopefully the changes I made helped as well, I did make some changes to the Main code..
I will leave this open for a few more days just in case....

**Comment by Eliminater74** [comment] 2023-12-06 20:58
Issue fixed and closed..

**Closed as completed by Eliminater74** 2023-12-06 20:58 UTC
